### ISSUE TITLE
Refactor the create card function and make one request instead of two

### ISSUE THREAD

**Issue by ahmadfarid-059** [GSG-G10/Trading-View---team-4#24]
## Tasks

- [x]  Remove empty divs in HTML code
- [x] Delete the Price url and work on one url 'changes'
- [x] add DOM functions for price changes to create card function
- [x] create the container divs in create card function
- [x] edit variables names
